/*
 * This code is generated by "Groovy - EasyB - Selenium RC" format.
 * Please refer to following URLs for:
 * 1) More Information:
 * http://limcheekin.blogspot.com/2009/07/behavior-driven-development-generating.html
 * 2) Latest Source Code:
 * https://vobject.svn.sourceforge.net/svnroot/vobject/grails/misc/trunk/groovy-easyb-rc.txt
 */

import com.thoughtworks.selenium.*
import java.util.regex.Pattern

before "start selenium", {
  given "selenium is up and running", {
    selenium = new DefaultSelenium("localhost",
               4444, "*firefox", "https://webgate.ec.europa.eu/fpfis/cms/isa/acceptance/")
    selenium.start()
  }
}

scenario "Enter scenario description here", {
  then "Enter any description here", {
    selenium.open("/fpfis/cms/isa/acceptance/")
    selenium.click("link=Login")
    selenium.waitForPageToLoad("60000")
    selenium.type("edit-name", "Marc Kimpe")
    selenium.type("edit-pass", "mkimpe123")
    selenium.click("edit-submit")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=Propose a news item")
    selenium.waitForPageToLoad("60000")
    selenium.type("edit-title", "test mkimpe")
    selenium.type("edit-title", "test mkimpe 1")
    selenium.type("edit-field-email-0-value", "marc.kimpe")
    selenium.type("edit-field-email-0-value", "marc.kimpe@cronos.be")
    selenium.click("edit-taxonomy-18-408")
    selenium.click("edit-taxonomy-18-410")
    selenium.click("edit-taxonomy-18-413")
    selenium.click("edit-taxonomy-16-341")
    selenium.click("edit-submit")
    selenium.waitForPageToLoad("60000")
    selenium.type("edit-field-source-url-0-title", "test mkimpe 1")
    selenium.type("edit-field-source-url-0-url", "http://www.google.be")
    selenium.click("//input[@id='edit-submit' and @name='op' and @value='Save']")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=View")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=Logout")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=Login")
    selenium.waitForPageToLoad("60000")
    selenium.type("edit-name", "Marc Kimpe")
    selenium.type("edit-pass", "mkimpe123")
    selenium.click("edit-submit")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=News")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=test mkimpe 1")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=Edit")
    selenium.waitForPageToLoad("60000")
    // pause(120)
    selenium.click("edit-delete")
    selenium.waitForPageToLoad("60000")
    selenium.click("edit-submit")
    selenium.waitForPageToLoad("60000")
    selenium.click("link=Logout")
    selenium.waitForPageToLoad("60000")
  }
}

after "stop selenium", {
  then "selenium should be shutdown", {
    selenium.stop()
  }
}
